### Create a film 
POST http://localhost:3000/films
Content-Type: application/json

{
    "id":4,
    "title": "Naruto",
    "duration":90,
    "budget":3,
    "link":"https://www.imdb.com/title/tt0476680/?ref_=ttls_li_tt"
}

### Read one pizza
@baseURL = http://localhost:3000

GET {{baseURL}}/films/3

### READ all with filter
GET {{baseURL}}/films?minimum-duration=104


